### ISSUE TITLE
Using p instead of div after enter key?

### ISSUE THREAD

**Issue by Kukulkano** [yusufsefasezer/ysEditor.js#1]
Hi. I like this editor project very much! Especially the focus on basic formatting and preventing all the bells and whistles makes it super useful and small for my project. Thank you!

Sadly, I just found that every hit on the enter key creates a new div tag instead of some p tag. Is this something I can change? Most regular WYSIWYG text editors creating a new paragraph on hitting enter. If you want some linebreak, you have to hit Shift+Enter.

Is there a setting to make ysEditor behave like this?

I initialize the editor like this:
```
globalEditor = new ysEditor({
        wrapper: "#edi_message", // Editor wrapper

        // Toolbar options
        bottom: true,
        toolbar: [
            "bold", "italic", "underline",
            "ol", "ul",
        ],

        // Content options
        scroll: true,
        includeContent: false,

        // Footer options
        footer: false,
        footerText: ""
    });
```

**Comment by yusufsefasezer** [comment]
Hi. I'm glad you liked it. Less is more!

In fact, by default it creates a new p tag every time enter is pressed. 

You can get the HTML code with ``globalEditor.getHTML();``

You can follow the steps below.

https://yusufsefasezer.github.io/ysEditor.js/examples/example-5-custombutton.html

Then hit to enter, open the browser console, you can get HTML code with ``myEditor.getHTML();``

Regards

**Comment by Kukulkano** [comment]
Thank you, but it does not work for me (Firefox 115.11). I just tested on jsfiddle.net and codepen.io and pasted the following code:
```
<html>

  <head>
    <script src="https://yusufsefasezer.github.io/ysEditor.js/dist/js/yseditor.min.js"></script>
    <link rel="stylesheet" href="https://yusufsefasezer.github.io/ysEditor.js/dist/css/yseditor.min.css" />
  </head>

  <body>
    <h1>Test</h1>
    <div id="yseditor" style="width: 100%; border: 1px solid blue;"></div>
    <script>
      var myEditor = new ysEditor({
        wrapper: "#yseditor", // Editor wrapper

        // Toolbar options
        toolbar: [
          "bold", "italic", "underline"
        ],
        bottom: true,

        // Content options
        height: 200,
        scroll: true,
        includeContent: false,

        // Footer options
        footer: false
      });

    </script>
    <button onclick="alert(myEditor.getHTML());">Get HTML content</button>

  </body>

</html>
```

If I manually enter a few lines of text and click the button, I just get a list of div elements instead of p?

Maybe I'm doing an error or forgot to set an option?

**Comment by yusufsefasezer** [comment]
Could you try this.

```html
<html>

  <head>
    <script src="https://yusufsefasezer.github.io/ysEditor.js/dist/js/yseditor.min.js"></script>
    <link rel="stylesheet" href="https://yusufsefasezer.github.io/ysEditor.js/dist/css/yseditor.min.css" />
  </head>

  <body>
    <h1>Test</h1>
    <div id="yseditor" style="width: 100%; border: 1px solid blue;"></div>
    <script>
      var myEditor = new ysEditor({
        wrapper: "#yseditor", // Editor wrapper

        // Toolbar options
        toolbar: [
          "bold", "italic", "underline"
        ],
        bottom: true,

        // Content options
        height: 200,
        scroll: true,
        includeContent: false,

        // Footer options
        footer: false
      });
    document.execCommand('defaultParagraphSeparator', false, 'p');
    </script>
    <button onclick="alert(myEditor.getHTML());">Get HTML content</button>

  </body>

</html>
``` 

This problem is related to browser behavior. You can change the default behavior as follows ``document.execCommand('defaultParagraphSeparator', false, 'p');``

Regards

**Comment by Kukulkano** [comment]
Thank you, this works! 

Maybe ysEditor should identify the need for this automatically to get similar behaviour on all major webbrowsers by default?

**Comment by yusufsefasezer** [comment]
Thank you too!

Good idea, I note this suggestion to add.
